

program ::=
  (statement)*;

statement ::=
  global_definition || ...;

global_definition ::=
  DEF type ID expr;

type ::=
  id ||
  # struct_type ||
  # array_type ||
  ...; # (LCARROT ID (COMMA ID)* RCARROT)?;

id ::=
  (ID RES)* ID;

expression ::=
  scoped_expression ||
  ...;

scoped_expression ::=
  LPAREN expression RPAREN;

nat_literal ::= NAT_LIT;





### Punctuation
SEMI = ";"
COMMA = ","
RES = "::"
LCARROT = "<"
RCARROT = ">"
LPAREN = "("
RPAREN = ")"

### Keywords
KW_MUT = "mut"
KW_CONST = "const"
KW_DEF = "def"

### Operators
ASSIGN = "="

### ID
ID = "[a-zA-Z]\w*"

### Literals
NAT_LIT = "0(\d|_)+"